### ISSUE TITLE
You cannot access body after reading from request's data stream

### ISSUE THREAD

**Issue by artel1992** [PaulGilmartin/graph_wrap#5]
When I try send query I get this error:
```json
{
    "errors": [
        {
            "message": "You cannot access body after reading from request's data stream"
        }
    ]
}
```
And I cannot understand why?
Python 3.9.4
Django 3.2
settings
```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "graphene_django",
    'rest_framework',
    'account',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```
account.models 
```python
class User(AbstractUser):
        father_name = models.CharField(max_length=255, null=True, blank=True)
        birth_date = models.DateField(null=True, blank=True)

        @property
        def age(self):
            age = datetime.date.today() - self.birth_date
            return age.days // 360
```
account.serializers
```python
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['id', 'username', 'last_name', 'first_name', 'father_name']
```
account.viewsets
```python
class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
```
urls
```python
urlpatterns = [path('admin/', admin.site.urls)]
urlpatterns.append(path(r'account/', include(router.urls)))
urlpatterns.append(path(r'graph/', view=graphql_view))
```
and query body
```
query{
    all_users{
        id,last_name,first_name,father_name
    }
}
```

**Comment by PaulGilmartin** [comment]
@artel1992 thanks for raising! 
That error looks strange. I've certainly encountered it before whilst using Django, but never whilst using GraphWrap. It's usually an indication that some piece of code is attempting to access request.POST (see https://stackoverflow.com/questions/19581110/exception-you-cannot-access-body-after-reading-from-requests-data-stream).

I made a test branch where I edited my unit tests to recreate your environment as close as possible, but I cannot create the issue:
https://github.com/PaulGilmartin/graph_wrap/pull/6/commits/c6426404181cb861ce9dfeec68cb22ea0036e45d

Are there any places in your project which are accessing request.POST?

**Comment by artel1992** [comment]
No,It hasn't place accessing request.POST. I disabled all midlewares but it didn't help.. I changed content type from json to x-www-form-urlencoded and it work. But I don't understand how type I need to use. Why I cannot use application /graph or json?

**Comment by PaulGilmartin** [comment]
Hmm OK. As you can see in the above PR, I do use content_type="application/json" in my unit test when I attempt to recreate your issue. If I use content_type="application/x-www-form-urlencoded", I get a 400 with error "Must provide query string". I also tested application/json content-type via a REST HTTP client and it seems to work
![image](https://user-images.githubusercontent.com/18212082/115533605-2cc80700-a297-11eb-83bd-8fad5f58158e.png)

**Comment by PaulGilmartin** [comment]
Can you provide any more data/screen shots on the request/responses?

**Comment by artel1992** [comment]
![image](https://user-images.githubusercontent.com/25362233/115548218-e4691300-a2af-11eb-87b1-bd8e00d4936b.png)
![image](https://user-images.githubusercontent.com/25362233/115548251-ec28b780-a2af-11eb-8e6f-5ba96306ddbb.png)

**Comment by artel1992** [comment]
![image](https://user-images.githubusercontent.com/25362233/115548309-01054b00-a2b0-11eb-86d3-6ca6356f47b5.png)
![image](https://user-images.githubusercontent.com/25362233/115548332-082c5900-a2b0-11eb-86df-dbe34085f824.png)

**Comment by artel1992** [comment]
maybe the problem is in the postman, what are you using to check the api?

**Comment by PaulGilmartin** [comment]
@artel1992 Hmm. I'm using the insomnia client (https://insomnia.rest/). If I get a chance I'll try to download postman later today and recreate the issue. Would be weird if that was the cause though.
In your second screen shot, what happens if you select "GraphQL" instead of x-www-form-urlencoded? That's certainly what I'm always using on insomina:

Edit: Ah sorry I see you did already try that, you can ignore last sentence.
![image](https://user-images.githubusercontent.com/18212082/115552192-517aa980-a2ac-11eb-9139-034a5aa8cceb.png)

**Comment by artel1992** [comment]
When I turn on the graph scheme I have a problem.

**Comment by artel1992** [comment]
I will try insomnia.rest

**Comment by artel1992** [comment]
![image](https://user-images.githubusercontent.com/25362233/115560590-67449a80-a2bd-11eb-9961-8df7bd8963c3.png)
((

**Comment by artel1992** [comment]
I have uploaded the code to github. If you have the time and opportunity to check it, I would be very glad. Sorry
https://github.com/artel1992/borkov

**Comment by artel1992** [comment]
https://github.com/artel1992/borkov/commit/302f5c4edaf3470aff3767848ed8c6f631c51eb5
it work

**Comment by PaulGilmartin** [comment]
@artel1992 thanks for uploading your code. Glad you've found a patch, but I'd still like to understand the root cause of the issue - seems very strange. I'll try to pull your branch tonight and investigate.

**Comment by artel1992** [comment]
Thank you too

**Comment by PaulGilmartin** [comment]
@artel1992 I've managed to recreate the issue on your branch, but I haven't got to the bottom of why it happens. I can only recreate it via an HTTP Client - can't get it to work in a unit test.

The code which invokes the error is in /graphene_django/views.parse_body. The line
```
        elif content_type == "application/json":
            # noinspection PyBroadException
            try:
                body = request.body.decode("utf-8")
            except Exception as e:
                raise HttpError(HttpResponseBadRequest(str(e)))
```
will throw the error if request._read_started is True. I'm trying to find out what is setting request._read_started to be True by this point. Debugging shows that it happens here in django.util.decorators. 
```
                if hasattr(middleware, 'process_view'):
                    result = middleware.process_view(request, view_func, args, kwargs)
```

Will keep digging! Looks like it has something to do with crsf (APIView.as_view returns `csrf_exempt(view)` which is the code middleware referenced above.

**Comment by artel1992** [comment]
Thank you very much

**Comment by PaulGilmartin** [comment]
Note to self:
request.POST is first read here:
```
            if request.method == "POST":
                try:
                    request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
                except OSError:
                    # Handle a broken connection before we've completed reading
                    # the POST data. process_view shouldn't raise any
                    # exceptions, so we'll ignore and serve the user a 403
                    # (assuming they're still listening, which they probably
                    # aren't because of the error).
                    pass
```
This line is only executed when _dont_enforce_csrf_checks is False (and _dont_enforce_csrf_checks is always false in unit tests by defaultt, which is why this couldn't be recreated there. It's also only executed if request.is_secure() is False (i.e. using http instead of https). See last comment here: https://groups.google.com/g/django-users/c/fCihqaR98ac

**Comment by PaulGilmartin** [comment]
@artel1992 I'll summarise the issue and my proposed fix.

The problem arises when `django.middleware.csrf.py` first reads the `request.POST` here
```
            if request.method == "POST":
                try:
                    request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
                except OSError:
                    # Handle a broken connection before we've completed reading
                    # the POST data. process_view shouldn't raise any
                    # exceptions, so we'll ignore and serve the user a 403
                    # (assuming they're still listening, which they probably
                    # aren't because of the error).
                    pass
```
and then subsequently `request.body` is accessed in /graphene_django/views.parse_body, which causes the error we saw. The reason we get into this code path seems to be due to the fact that the `graphql_view` function is wrapped in the decorator `rest_framework.decorators.api_view`, which when combined with /graphene_django/views.parse_body gives this error. 

After reading about csrf exemption in graphene-django (see https://github.com/graphql-python/graphene-django/issues/170), my proposed fix, which I believe to be secure, is to no longer wrap graphql_view in api_view, but to wrap it in `csrf_exempt`. I have tested this locally and it fixes the issue we're seeing here. I also believe it to be at least no less secure than what we already have, since `rest_framework.decorators.api_view` is returning a view wrapped in csrf_exempt as well (it's just doing it at the "wrong" time when combined with graphen_django):
```
    @classmethod
    def as_view(cls, **initkwargs):
        """
        Store the original class on the view function.

        This allows us to discover information about the view when we do URL
        reverse lookups.  Used for breadcrumb generation.
        """
        if isinstance(getattr(cls, 'queryset', None), models.query.QuerySet):
            def force_evaluation():
                raise RuntimeError(
                    'Do not evaluate the `.queryset` attribute directly, '
                    'as the result will be cached and reused between requests. '
                    'Use `.all()` or call `.get_queryset()` instead.'
                )
            cls.queryset._fetch_all = force_evaluation

        view = super().as_view(**initkwargs)
        view.cls = cls
        view.initkwargs = initkwargs

        # Note: session based authentication is explicitly CSRF validated,
        # all other authentication is CSRF exempt.
        return csrf_exempt(view)
```
I will make this fix later today unless I think of a reason not to.

**Comment by artel1992** [comment]
Much obliged to you

**Comment by artel1992** [comment]
Can I close the issue?

**Comment by PaulGilmartin** [comment]
@artel1992 i'll close it later once I push the fix :)

**Comment by PaulGilmartin** [comment]
fixed in release 0.1.1

**Comment by artel1992** [comment]
so.. it wok, thank... but I have another issue how create mutations?
like in graphene?

**Comment by PaulGilmartin** [comment]
Graphwrap currently only supports queries i’m afraid! You can see that in
readme.md. I may add support for mutations in the future, but i think it’ll
be difficult :)

**Comment by artel1992** [comment]
Okay, Thanks
